### PR TITLE
Fix issues in mobile screen

### PR DESCRIPTION
**Pull request by marioskranitsas**

### CODE REVIEW

**Comment by dedywahyudi** [comment]
@marioskranitsas Please check and fix these feedback.
Let me know for any questions

1. Banner on the basic info page is different:
- remove the padding left & right so the top area use full width

2. The price and days row icons are not aligned on the basic info page
- "?" need use green color & placed on the right side

3. Too many spaces in Project title section/Your industry section/after ' Styles & themes' section/
- look good 

4. The separation line is missing before ‘Your Industry’ section
- look good

5. Design shows 3 colors ina row but the app has only 2 in a row
- Need reduce padding on the right side. Or make all colors centered

6. Default text not visible in color specify field and too many spaces before it
- need top spacing above the text. Is font size correct?

7. The Save for later button and submit buttons deviates from the design
- Save later need to be icon, and both save & review need to be aligned

8. Banner on the Review and payment page is different:
- background still look different

9. The price and days row icons are not aligned on the Review and payment page
- "?" need use green color & placed on the right side

10. Alignment issue in the checkbox text on payment section
- still not fixed, follow design to make the Understand text and Order Contact link inline

11. There’s an outline when the colors are selected
- look good

12. The save for later button is not visible
- Save for later need to be icon


STYLE & THEME
- All boxes need centered
- When modal window show up, modal not use full width? Content not visible

**Comment by marioskranitsas** [comment]
@dedywahyudi i think that the Save for later icon is not the correct icon on figma , can i have the correct one?
everything else is ready

**Comment by dedywahyudi** [comment]
@marioskranitsas This icon?

Icon-save

**Comment by marioskranitsas** [comment]
yes , is this the Save For Later icon ?

**Comment by dedywahyudi** [comment]
Yes, this is save later icon from Figma

**Comment by marioskranitsas** [comment]
@dedywahyudi ok , thank you

**Comment by marioskranitsas** [comment]
I cannot export the save for later icon from https://www.figma.com/file/2t8Wcyu8FAXxzQGpyK8r4f/TC-Design-System-2.0-%2F-2022?node-id=115%3A2612 as exporting is disabled. Please provide the icon file so I can fix the last issue

**Comment by marioskranitsas** [comment]
I have created a new PR here https://github.com/topcoder-platform/mfe-customer-work/pull/377 as I was getting an error trying to push to this one

**Comment by dedywahyudi** [comment]
@marioskranitsas The svg above not works? You can download and use that save for later icon

**Comment by ThomasKranitsas** [comment]
@dedywahyudi just to make sure, was the review done using this PR or using https://github.com/topcoder-platform/mfe-customer-work/pull/377 ?

Can we close this PR to avoid confusion?

@marioskranitsas please see the above feedback and fix the remaining issues so we can close this ticket out.

**Comment by dedywahyudi** [comment]
@ThomasKranitsas 

Hm, i tested using this PR. 

@marioskranitsas Which one that covers all mobile issue feedback?

**Comment by marioskranitsas** [comment]
@dedywahyudi yes , Please use this #377

**Pull request closed without merging**
