### PR TITLE
Prod 1877 mark as done modal issues

### PR DESCRIPTION
**Pull request by vas3a**
[PROD-1877](https://topcoder.atlassian.net/browse/PROD-1877)

- fix stars tooltip
- fix hover issue in mark as done modal
- update styling for mark as done modal

to make the button "mark as done" visible please commend this in WorkDetailHeader.tsx: 
image

### CODE REVIEW

**Review by testflyjets — CHANGES_REQUESTED** [review]
The behavior of the rating stars seems to be broken -- see the attached screencast.

https://user-images.githubusercontent.com/160552/168144036-dda50d79-b393-412b-b047-a1da6010f566.mov

**Comment by vas3a** [comment]
@testflyjets makes sense to me! @brooketopcoder do you agree re tooltip?

**Comment by brooketopcoder** [comment]
> @testflyjets makes sense to me! @brooketopcoder do you agree re tooltip?

go for it!

**Comment by vas3a** [comment]
@brooketopcoder @testflyjets this one is done! Thanks!

**Review by testflyjets — APPROVED** [review]

**Pull request merged**
